### ISSUE TITLE
column workspace_id does not exist

### ISSUE THREAD

**Issue by Darshan-V** [vishu2222/diskord#35]
error: column "workspace_id" does not exist
    at Parser.parseErrorMessage (/home/darshan/geekskool/diskord/Backend/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/darshan/geekskool/diskord/Backend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/darshan/geekskool/diskord/Backend/node_modules/pg-protocol/dist/parser.js:39:38)
    at TLSSocket.<anonymous> (/home/darshan/geekskool/diskord/Backend/node_modules/pg-protocol/dist/index.js:11:42)
    at TLSSocket.emit (node:events:512:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 111,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '8',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3661',
  routine: 'errorMissingColumn'
}

**Comment by reddy-vishwanath** [comment]
fixed the issue
